### ISSUE TITLE
Se borra el archivo strings.es.json

### ISSUE THREAD

**Issue by juque** [bootic/bootic_cli#18]
Se borra el archivo strings.es.json — si clonas una tienda (que tenga estos archivos), haces cualquier cambio en ella, luego haces push lo borra, así de simple.

<img width="849" alt="Captura de pantalla 2023-02-21 a la(s) 09 56 51" src="https://user-images.githubusercontent.com/36350/220350898-bf8de6fc-3646-4202-a03a-b0b745b8af22.png">

**Comment by tomas** [comment]
Chanfles, lo reviso ahora.

**Comment by tomas** [comment]
OK, fixed in v0.9.1
